[theme]
base = "light"
primaryColor = "#10b981"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
